import { CellType } from "./components/GridViz";

// Shared wall layout for consistent comparison
const WALLS: [number, number][] = [
  [1, 3], [2, 3], [3, 3], [4, 3],
  [3, 5], [3, 6], [3, 7],
  [5, 6], [6, 6], [6, 7],
  [1, 7], [1, 8],
];

const START: [number, number] = [1, 1];
const END: [number, number] = [6, 8];

// BFS explores level by level (like ripples)
const BFS_STEPS: [number, number, CellType][] = [
  [1, 0, "frontier"], [1, 2, "frontier"], [0, 1, "frontier"], [2, 1, "frontier"],
  [1, 0, "visited"], [0, 0, "frontier"], [2, 0, "frontier"],
  [1, 2, "visited"], [0, 2, "frontier"], [2, 2, "frontier"],
  [0, 1, "visited"],
  [2, 1, "visited"], [3, 1, "frontier"],
  [0, 0, "visited"],
  [2, 0, "visited"], [3, 0, "frontier"],
  [0, 2, "visited"], [0, 3, "frontier"],
  [2, 2, "visited"], [2, 4, "frontier"],
  [3, 1, "visited"], [4, 1, "frontier"], [3, 2, "frontier"],
  [3, 0, "visited"], [4, 0, "frontier"],
  [2, 4, "visited"], [2, 5, "frontier"], [1, 4, "frontier"],
  [4, 1, "visited"], [5, 1, "frontier"], [4, 2, "frontier"],
  [3, 2, "visited"],
  [4, 0, "visited"], [5, 0, "frontier"],
  [2, 5, "visited"], [2, 6, "frontier"], [1, 5, "frontier"],
  [1, 4, "visited"], [0, 4, "frontier"], [1, 5, "frontier"],
  [5, 1, "visited"], [5, 2, "frontier"], [6, 1, "frontier"],
  [4, 2, "visited"], [4, 4, "frontier"],
  [5, 0, "visited"], [6, 0, "frontier"],
  [2, 6, "visited"], [2, 7, "frontier"], [1, 6, "frontier"],
  [1, 5, "visited"], [0, 5, "frontier"],
  [5, 2, "visited"], [5, 3, "frontier"],
  [6, 1, "visited"], [7, 1, "frontier"], [6, 2, "frontier"],
  [4, 4, "visited"], [4, 5, "frontier"], [5, 4, "frontier"],
  [6, 0, "visited"], [7, 0, "frontier"],
  [5, 3, "visited"], [5, 4, "frontier"],
  [4, 5, "visited"], [4, 6, "frontier"],
  [5, 4, "visited"], [5, 5, "frontier"],
  [5, 5, "visited"], [6, 5, "frontier"],
  [6, 5, "visited"], [7, 5, "frontier"], [6, 4, "frontier"],
  [7, 5, "visited"], [7, 6, "frontier"],
  [7, 6, "visited"], [7, 7, "frontier"],
  [7, 7, "visited"], [7, 8, "frontier"],
  [7, 8, "visited"], [6, 8, "path"],
  // Path
  [7, 7, "path"], [7, 6, "path"], [7, 5, "path"],
  [6, 5, "path"], [5, 5, "path"], [5, 4, "path"],
  [4, 4, "path"], [4, 2, "path"], [3, 2, "path"],
  [3, 1, "path"], [2, 1, "path"], [1, 1, "path"],
];

// DFS goes deep first (may not find shortest path)
const DFS_STEPS: [number, number, CellType][] = [
  [0, 1, "frontier"], [2, 1, "frontier"], [1, 0, "frontier"], [1, 2, "frontier"],
  [1, 2, "visited"], [0, 2, "frontier"], [2, 2, "frontier"],
  [2, 2, "visited"], [2, 4, "frontier"],
  [2, 4, "visited"], [1, 4, "frontier"], [2, 5, "frontier"],
  [2, 5, "visited"], [1, 5, "frontier"], [2, 6, "frontier"],
  [2, 6, "visited"], [1, 6, "frontier"], [2, 7, "frontier"],
  [2, 7, "visited"], [2, 8, "frontier"],
  [2, 8, "visited"], [1, 8, "frontier"],
  [2, 7, "visited"],
  [1, 6, "visited"], [0, 6, "frontier"],
  [0, 6, "visited"], [0, 7, "frontier"],
  [0, 7, "visited"], [0, 8, "frontier"],
  [0, 8, "visited"],
  [1, 5, "visited"], [0, 5, "frontier"],
  [0, 5, "visited"], [0, 4, "frontier"],
  [0, 4, "visited"], [0, 3, "frontier"],
  [1, 4, "visited"],
  [0, 1, "visited"], [0, 0, "frontier"],
  [0, 0, "visited"],
  [2, 1, "visited"], [3, 1, "frontier"],
  [3, 1, "visited"], [4, 1, "frontier"], [3, 0, "frontier"], [3, 2, "frontier"],
  [3, 2, "visited"], [4, 2, "frontier"],
  [4, 2, "visited"], [4, 4, "frontier"],
  [4, 4, "visited"], [5, 4, "frontier"], [4, 5, "frontier"],
  [4, 5, "visited"], [4, 6, "frontier"],
  [4, 6, "visited"], [4, 7, "frontier"],
  [4, 7, "visited"], [4, 8, "frontier"],
  [4, 8, "visited"], [5, 8, "frontier"],
  [5, 8, "visited"], [6, 8, "path"],
  // Path (not shortest!)
  [5, 8, "path"], [4, 8, "path"], [4, 7, "path"],
  [4, 6, "path"], [4, 5, "path"], [4, 4, "path"],
  [4, 2, "path"], [3, 2, "path"], [3, 1, "path"],
  [2, 1, "path"], [1, 1, "path"],
];

// Dijkstra explores by cost (optimal for weighted graphs)
const DIJKSTRA_STEPS: [number, number, CellType][] = [
  [1, 0, "frontier"], [1, 2, "frontier"], [0, 1, "frontier"], [2, 1, "frontier"],
  [1, 0, "visited"], [0, 0, "frontier"], [2, 0, "frontier"],
  [0, 1, "visited"],
  [1, 2, "visited"], [0, 2, "frontier"], [2, 2, "frontier"],
  [2, 1, "visited"], [3, 1, "frontier"],
  [0, 0, "visited"],
  [2, 0, "visited"], [3, 0, "frontier"],
  [0, 2, "visited"],
  [2, 2, "visited"], [2, 4, "frontier"],
  [3, 1, "visited"], [4, 1, "frontier"], [3, 2, "frontier"],
  [3, 0, "visited"], [4, 0, "frontier"],
  [2, 4, "visited"], [2, 5, "frontier"], [1, 4, "frontier"],
  [3, 2, "visited"],
  [4, 1, "visited"], [5, 1, "frontier"],
  [4, 0, "visited"], [5, 0, "frontier"],
  [2, 5, "visited"], [2, 6, "frontier"], [1, 5, "frontier"],
  [1, 4, "visited"], [0, 4, "frontier"],
  [5, 1, "visited"], [5, 2, "frontier"], [6, 1, "frontier"],
  [5, 0, "visited"], [6, 0, "frontier"],
  [5, 2, "visited"], [5, 3, "frontier"],
  [6, 1, "visited"], [7, 1, "frontier"], [6, 2, "frontier"],
  [5, 3, "visited"], [5, 4, "frontier"], [4, 4, "frontier"],
  [5, 4, "visited"], [5, 5, "frontier"],
  [4, 4, "visited"], [4, 5, "frontier"],
  [5, 5, "visited"], [6, 5, "frontier"],
  [6, 5, "visited"], [7, 5, "frontier"], [6, 4, "frontier"],
  [7, 5, "visited"], [7, 6, "frontier"],
  [7, 6, "visited"], [7, 7, "frontier"],
  [7, 7, "visited"], [7, 8, "frontier"],
  [7, 8, "visited"], [6, 8, "path"],
  [7, 7, "path"], [7, 6, "path"], [7, 5, "path"],
  [6, 5, "path"], [5, 5, "path"], [5, 4, "path"],
  [5, 3, "path"], [5, 2, "path"], [5, 1, "path"],
  [4, 1, "path"], [3, 1, "path"], [2, 1, "path"], [1, 1, "path"],
];

// A* uses heuristic to guide search (most efficient)
const ASTAR_STEPS: [number, number, CellType][] = [
  [2, 1, "frontier"], [1, 2, "frontier"], [1, 0, "frontier"], [0, 1, "frontier"],
  [2, 1, "visited"], [3, 1, "frontier"], [2, 2, "frontier"], [2, 0, "frontier"],
  [1, 2, "visited"], [2, 2, "frontier"],
  [2, 2, "visited"], [2, 4, "frontier"],
  [3, 1, "visited"], [3, 2, "frontier"], [4, 1, "frontier"],
  [3, 2, "visited"], [4, 2, "frontier"],
  [2, 4, "visited"], [2, 5, "frontier"], [1, 4, "frontier"],
  [4, 2, "visited"], [4, 4, "frontier"],
  [4, 1, "visited"], [5, 1, "frontier"],
  [2, 5, "visited"], [2, 6, "frontier"],
  [4, 4, "visited"], [5, 4, "frontier"], [4, 5, "frontier"],
  [5, 4, "visited"], [5, 5, "frontier"],
  [5, 5, "visited"], [6, 5, "frontier"],
  [6, 5, "visited"], [7, 5, "frontier"],
  [7, 5, "visited"], [7, 6, "frontier"],
  [7, 6, "visited"], [7, 7, "frontier"],
  [7, 7, "visited"], [7, 8, "frontier"],
  [7, 8, "visited"], [6, 8, "path"],
  [7, 7, "path"], [7, 6, "path"], [7, 5, "path"],
  [6, 5, "path"], [5, 5, "path"], [5, 4, "path"],
  [4, 4, "path"], [4, 2, "path"], [3, 2, "path"],
  [3, 1, "path"], [2, 1, "path"], [1, 1, "path"],
];

// Greedy just chases the heuristic
const GREEDY_STEPS: [number, number, CellType][] = [
  [2, 1, "frontier"], [1, 2, "frontier"],
  [2, 1, "visited"], [2, 2, "frontier"], [3, 1, "frontier"],
  [2, 2, "visited"], [2, 4, "frontier"],
  [2, 4, "visited"], [2, 5, "frontier"], [1, 4, "frontier"],
  [2, 5, "visited"], [2, 6, "frontier"],
  [2, 6, "visited"], [2, 7, "frontier"],
  [2, 7, "visited"], [2, 8, "frontier"],
  [2, 8, "visited"], [1, 8, "frontier"],
  [1, 8, "visited"],
  // backtracks
  [3, 1, "visited"], [4, 1, "frontier"], [3, 2, "frontier"],
  [4, 1, "visited"], [5, 1, "frontier"],
  [5, 1, "visited"], [5, 2, "frontier"], [6, 1, "frontier"],
  [5, 2, "visited"], [5, 3, "frontier"],
  [5, 3, "visited"], [5, 4, "frontier"],
  [5, 4, "visited"], [5, 5, "frontier"],
  [5, 5, "visited"], [6, 5, "frontier"],
  [6, 5, "visited"], [7, 5, "frontier"],
  [7, 5, "visited"], [7, 6, "frontier"],
  [7, 6, "visited"], [7, 7, "frontier"],
  [7, 7, "visited"], [7, 8, "frontier"],
  [7, 8, "visited"], [6, 8, "path"],
  [7, 7, "path"], [7, 6, "path"], [7, 5, "path"],
  [6, 5, "path"], [5, 5, "path"], [5, 4, "path"],
  [5, 3, "path"], [5, 2, "path"], [5, 1, "path"],
  [4, 1, "path"], [3, 1, "path"], [2, 1, "path"], [1, 1, "path"],
];

// UCS is same as Dijkstra for uniform weights
const UCS_STEPS = DIJKSTRA_STEPS;

export const ALGO_CONFIGS = [
  {
    name: "Breadth-First Search",
    subtitle: "Explores all neighbors at the current depth before moving deeper. Guarantees shortest path in unweighted graphs.",
    dataStructure: "Queue (FIFO)",
    complexity: "O(V + E)",
    optimal: true,
    pseudocode: [
      "BFS(start, goal):",
      "  queue ← [start]",
      "  visited ← {start}",
      "  while queue not empty:",
      "    node ← queue.dequeue()",
      "    if node = goal: return path",
      "    for neighbor of node:",
      "      if neighbor ∉ visited:",
      "        queue.enqueue(neighbor)",
    ],
    gridSteps: BFS_STEPS,
    walls: WALLS,
    startPos: START,
    endPos: END,
    accentColor: COLORS.cobalt,
    number: 1,
  },
  {
    name: "Depth-First Search",
    subtitle: "Dives as deep as possible before backtracking. Fast but does NOT guarantee the shortest path.",
    dataStructure: "Stack (LIFO)",
    complexity: "O(V + E)",
    optimal: false,
    pseudocode: [
      "DFS(start, goal):",
      "  stack ← [start]",
      "  visited ← {}",
      "  while stack not empty:",
      "    node ← stack.pop()",
      "    if node = goal: return path",
      "    visited.add(node)",
      "    for neighbor of node:",
      "      stack.push(neighbor)",
    ],
    gridSteps: DFS_STEPS,
    walls: WALLS,
    startPos: START,
    endPos: END,
    accentColor: COLORS.crimson,
    number: 2,
  },
  {
    name: "Dijkstra's Algorithm",
    subtitle: "Always expands the lowest-cost node. Optimal for weighted graphs — the gold standard for shortest paths.",
    dataStructure: "Min-Heap",
    complexity: "O((V+E) log V)",
    optimal: true,
    pseudocode: [
      "Dijkstra(start, goal):",
      "  dist[start] ← 0",
      "  pq ← [(0, start)]",
      "  while pq not empty:",
      "    node ← pq.extract_min()",
      "    if node = goal: return path",
      "    for neighbor of node:",
      "      alt ← dist[node] + w(edge)",
      "      if alt < dist[neighbor]:",
      "        pq.insert(alt, neighbor)",
    ],
    gridSteps: DIJKSTRA_STEPS,
    walls: WALLS,
    startPos: START,
    endPos: END,
    accentColor: COLORS.yellow,
    number: 3,
  },
  {
    name: "Uniform Cost Search",
    subtitle: "Identical to Dijkstra but framed as a search algorithm. Expands the cheapest unexplored node first.",
    dataStructure: "Min-Heap",
    complexity: "O((V+E) log V)",
    optimal: true,
    pseudocode: [
      "UCS(start, goal):",
      "  cost[start] ← 0",
      "  pq ← [(0, start)]",
      "  while pq not empty:",
      "    node ← pq.extract_min()",
      "    if node = goal: return path",
      "    for neighbor of node:",
      "      new ← cost[node] + w(edge)",
      "      if new < cost[neighbor]:",
      "        pq.insert(new, neighbor)",
    ],
    gridSteps: UCS_STEPS,
    walls: WALLS,
    startPos: START,
    endPos: END,
    accentColor: COLORS.emerald,
    number: 4,
  },
  {
    name: "Greedy Best-First",
    subtitle: "Chases the heuristic — always expands the node closest to the goal. Fast but often not optimal.",
    dataStructure: "Min-Heap",
    complexity: "O((V+E) log V)",
    optimal: false,
    pseudocode: [
      "Greedy(start, goal):",
      "  pq ← [(h(start), start)]",
      "  visited ← {}",
      "  while pq not empty:",
      "    node ← pq.extract_min()",
      "    if node = goal: return path",
      "    visited.add(node)",
      "    for neighbor of node:",
      "      pq.insert(h(neighbor), n)",
    ],
    gridSteps: GREEDY_STEPS,
    walls: WALLS,
    startPos: START,
    endPos: END,
    accentColor: "#f97316",
    number: 5,
  },
  {
    name: "A* Search",
    subtitle: "The best of both worlds — uses f = g + h to find the optimal path while exploring fewer nodes than Dijkstra.",
    dataStructure: "Min-Heap",
    complexity: "O((V+E) log V)",
    optimal: true,
    pseudocode: [
      "A*(start, goal):",
      "  g[start] ← 0, f ← g + h",
      "  pq ← [(f, start)]",
      "  while pq not empty:",
      "    node ← pq.extract_min()",
      "    if node = goal: return path",
      "    for neighbor of node:",
      "      g' ← g[node] + w(edge)",
      "      if g' < g[neighbor]:",
      "        pq.insert(g'+h, neighbor)",
    ],
    gridSteps: ASTAR_STEPS,
    walls: WALLS,
    startPos: START,
    endPos: END,
    accentColor: COLORS.cyan,
    number: 6,
  },
] as const;

import { COLORS } from "./styles";
